name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: true
      matrix:
        project-type: [app, package]
        with-conventional-commits: [true, false]
        typing: [true, false]

    name: "Test ${{ matrix.project-type }} (conventional=${{ matrix.with-conventional-commits }}, typing=${{ matrix.typing }})"

    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          path: project-template

      - name: Set up uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0

      - name: Scaffold Python project
        run: |
          uvx copier copy --vcs-ref=HEAD project-template my-project \
            --defaults \
            --data project_type="${{ matrix.project-type }}" \
            --data project_name="Project Template" \
            --data project_description="A Python ${{ matrix.project-type }} that does things." \
            --data with_conventional_commits="${{ matrix.with-conventional-commits }}" \
            --data typing="${{ matrix.typing }}"
          cd my-project
          rm .copier-answers.yml
          git config --global user.email "test@example.com"
          git config --global user.name "Test User"
          git config --global init.defaultBranch main
          git init
          git add .
          git commit -m "Initial commit"

      - name: Run hooks
        uses: j178/prek-action@4e14d07f9231acabce116ccfca13b13dd9755ece # v3.0.0
        with:
          working-directory: ./my-project
